version: "3"

services:
    app:
        image: webdevops/php-nginx:7.4-alpine
        ports:
            - 8080:80
        working_dir: /app
        environment: 
            - WEB_DOCUMENT_ROOT=/app/public
        volumes:
            - './:/app'