name: CI-CD # Give your workflow a name

on:
  push:
    branches: [ master, gitflow ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        apt-get install zip -y
        mkdir ../build
        cp -TR . ../build
        zip -r deploy.zip ../build/

    - name: copy file via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_KNOWN_HOSTS }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "deploy.zip"
        target: "/home/cd"
